--CREATE TABLE champion (
--  no NUMBER(11) NOT NULL,
--  name VARCHAR2(255) NOT NULL,
--  title VARCHAR2(255) NOT NULL,
--  health NUMBER(5) DEFAULT 0 NOT NULL,
--  damage NUMBER(5) DEFAULT 0 NOT NULL,
--  h_regen NUMBER(3,2) DEFAULT 0.0 NOT NULL,
--  a_speed NUMBER(4,3) DEFAULT 0.0 NOT NULL,
--  mana NUMBER(5) DEFAULT 0 NOT NULL,
--  armor NUMBER(3) DEFAULT 0 NOT NULL,
--  m_regen NUMBER(3,2) DEFAULT 0.0 NOT NULL,
--  m_res NUMBER(3) DEFAULT 0 NOT NULL,
--  range NUMBER(5) DEFAULT 0 NOT NULL,
--  speed NUMBER(5) DEFAULT 0 NOT NULL,
--  description VARCHAR2(4000),
--  regdate DATE DEFAULT SYSDATE NOT NULL,
--  CONSTRAINT PK_CHAMPION PRIMARY KEY (no),
--  CONSTRAINT UK_CHAMPION_NAME UNIQUE (name)
--);

CREATE SEQUENCE SEQ_CHAMP
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
;

CREATE TABLE champ (
  no NUMBER(11) NOT NULL,
  name VARCHAR2(20) NOT NULL,
  type VARCHAR2(255) NOT NULL,
  health NUMBER(5) DEFAULT 0 NOT NULL,
  damage NUMBER(5) DEFAULT 0 NOT NULL,
  regdate DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CHAMP PRIMARY KEY (no),
  CONSTRAINT UK_CHAMP_NAME UNIQUE (name)
);